[versions]
java = "25"
google-java-format = "1.36.0"
graalvm = "25.2.4"
lsp4j = "1.0.0"
gson = "2.14.0"
junit = "6.0.1"
spotless = "8.10.0"
native-build-tools = "1.1.6"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
truffle-api = { module = "org.graalvm.truffle:truffle-api", version.ref = "graalvm" }
truffle-runtime = { module = "org.graalvm.truffle:truffle-runtime", version.ref = "graalvm" }
truffle-dsl-processor = { module = "org.graalvm.truffle:truffle-dsl-processor", version.ref = "graalvm" }
polyglot = { module = "org.graalvm.polyglot:polyglot", version.ref = "graalvm" }
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "native-build-tools" }
